### PR TITLE
Add some useful properties from json_state

### PR DESCRIPTION
**Pull request by dmwyatt**

### CODE REVIEW

**Comment by dmwyatt** [comment]
FYI, I want these exposed so I can add sensors to HA for them.

**Comment by eseglem** [comment]
I would also like to see this merged for the same reason.

**Comment by berg** [comment]
cc @w1ll1am23 — I'd love to have this merged as well!

**Comment by w1ll1am23** [comment]
Sorry everyone, githubs notifications are terrible and if I don't turn them off I get notifications for everything that happens in the home-assistant repo so the only way I get an email is if I am mentioned. I will take a look at these asap.

**Comment by berg** [comment]
Haha, thanks, I kinda figured that's what was going on!

**Comment by w1ll1am23** [comment]
I am in the process of uploading the new version to pypi now I won't have time in the next week at least to do any Home Assistant work to get these changes integrated so someone else feel free to do so.


As a side note, I have not EcoNet products at all. I created this library for the sole purpose of helping the EcoNet users out there get there stuff in Home Assistant. Having said that, I will continue to maintain this while I can, but if anyone is interested in taking over this library and the HA integration let me know.

Thanks.

**Pull request merged**
